baseurl = "https://neuropsychology.github.io/blog/"
languageCode = "en-us"
title = "Neuropsychology Blog"
theme = "hugo-lithium"
# googleAnalytics = "UA-97457476-5"
disqusShortname = ""
publishDir = "docs"
relativeURLs = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/neuropsychology/blog"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Dom_Makowski"

[params]
	author = "Dominique Makowski"
    description = "The technical aspect of neuroscience and psychology."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.PNG"
    width = 1198
    height = 1198
    alt = "Neuropsychology Blog"

